### ISSUE TITLE
Additional space was added to the end of the chef-client cron job which breaks the original validation

### ISSUE THREAD

**Issue by qiaodeli111** [chef-cookbooks/chef-client#623]
### Cookbook version
11.1.2

### Chef-client version
14

### Scenario:
When we are working with chef-client(10.0.0) and before, we validate the chef-client cron job configuration by:

```
describe cron do
  its(:table) { should match(%r{^\*/30 \* \* \* \* /bin/sleep [0-9]+; \(/usr/bin/knife tag list \$\(hostname\) \| /bin/grep chef_autoconverge_disable\) >/dev/null 2>&1 \|\| /bin/nice -n 19 /usr/bin/chef-client  --run-lock-timeout 0 > /dev/null 2>&1$}) }
end
```

But our test case was not acting with chef-client(11.1.2) because the additional space was added to the end of the cron job. (refer to chef-client::cron, row 143). That space was not there before March 2018...

```
    cmd << "#{client_bin} #{daemon_options}#{append_log} #{log_file} 2>&1 "
```

To fix this problem we removed the `$` of the end of our regular expression. 

To be honest, this is not a functional issue but when we were trying to figure out the reason, it cost us a lot of time...... I guess it is better to change back in case anybody like us meet the same situation. Thanks.

**Comment by welcomebot** [comment]
Hey There
It looks like this is the first issue you've filed against the chef-cookbooks project. I'm here to offer you a bit of extra help to make sure we can quickly get back to you.
 Make sure you've filled out all the fields in our issue template. Make sure you've provided us with the version of chef-client you're running, your operating system and the version of the cookbook. If you're not using the most up to date version of the cookbook then please make sure to update first. Lots of things change between versions even if you're issue isn't listed in the changelog. Finally please give us a detailed description of the issue you're having. The more we know about what you're trying to do, what actually happens, and how you can reproduce the problem, the better.

If you're looking for more immediate troubleshooting help make sure to check out #general on the Chef Community Slack. There's plenty of folks there willing to lend a helping hand. Thanks for the first issue. We hope we can get back to you soon with a solution.
