### PR TITLE
Feature/make handler optional

### LINKED ISSUE #529: TemplateError on windows 2012 => undefined method `each' for nil:NilClass
### Cookbook version
v9.0.0

### Chef-client version
chef-client 13.0.118

### Platform Details
Windows Server 2012 x64 (same on 2008R2 / 2012R2 / 2016)

### Scenario
Create a wrapper cookbook with including recipes from chef-client

### Analyse
This scenario was working fine on v8.1.8 with the same conditions.
The error seems to be caused by  following values:

` :start_handlers=>nil, :report_handlers=>nil, :exception_handlers=>nil`

that cause ` undefined method each for nil:NilClass`

### Steps to Reproduce
add this values in a wrapper cookbook:
```
include_recipe 'chef-client::config'
include_recipe 'chef-client::task'
include_recipe 'chef-client::delete_validation'
```

### Expected Result
chef-client cookbook manage the configuration of chef-client (client.rb).

### Actual Result
```
* template[c:\chef/client.rb] action create[2017-10-24T09:28:57+00:00] INFO: Processing template[c:\chef/client.rb] action create (chef-client::config line 78)
       
       
           ================================================================================
           Error executing action `create` on resource 'template[c:\chef/client.rb]'
           ================================================================================
       
           Chef::Mixin::Template::TemplateError
           ------------------------------------
           undefined method `each' for nil:NilClass
       
           Resource Declaration:
           ---------------------
           # In C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chef-client/recipes/config.rb
       
            78: template "#{node['chef_client']['conf_dir']}/client.rb" do
            79:   source 'client.rb.erb'
            80:   owner d_owner
            81:   group node['root_group']
            82:   mode '0644'
            83:   variables(
            84:     chef_config: node['chef_client']['config'],
            85:     chef_requires: chef_requires,
            86:     ohai_disabled_plugins: node['ohai']['disabled_plugins'],
            87:     ohai_new_config_syntax: Gem::Requirement.new('>= 8.6.0').satisfied_by?(Gem::Version.new(Ohai::VERSION)),
            88:     start_handlers: node['chef_client']['config']['start_handlers'],
            89:     report_handlers: node['chef_client']['config']['report_handlers'],
            90:     exception_handlers: node['chef_client']['config']['exception_handlers']
            91:   )
            92: 
            93:   if node['chef_client']['reload_config']
            94:     notifies :create, 'ruby_block[reload_client_config]', :immediately
            95:   end
            96: end
       
           Compiled Resource:
           ------------------
           # Declared in C:/Users/ADMINI~1/AppData/Local/Temp/kitchen/cache/cookbooks/chef-client/recipes/config.rb:78:in `from_file'
       
           template("c:\chef/client.rb") do
             action [:create]
             retries 0
             retry_delay 2
             default_guard_interpreter :default
             source "client.rb.erb"
             variables {:chef_config=>{"log_level"=>":info", "chef_server_url"=>"chefzero://localhost:8889", "client_key"=>"C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\client.pem", "validation_client_name"=>"chef-validator", "validation_key"=>"c:\\chef\\chef-validator.pem", "node_name"=>"default-windows-2012rtm", "http_proxy"=>nil, "https_proxy"=>nil, "fips"=>false, "file_cache_path"=>"c:\\chef\\cache", "rubygems_url"=>"https://rubygems.org/", "log_location"=>"C:/chef/log/client.log"}, :chef_requires=>[], :ohai_disabled_plugins=>[], :ohai_new_config_syntax=>true, :start_handlers=>nil, :report_handlers=>nil, :exception_handlers=>nil}
             declared_type :template
             cookbook_name "chef-client"
             recipe_name "config"
             owner "Administrator"
             group "Administrators"
             mode "0644"
             path "c:\\chef/client.rb"
             rights nil
             deny_rights nil
             verifications []
           end
       
           Template Context:
           -----------------
           on line #51
            49: 
            50: # Do not crash if a handler is missing / not installed yet
            51: begin
            52: <% @start_handlers.each do |handler| -%>
            53:   start_handlers << <%= handler["class"] %>.new(<%= handler["arguments"].join(',') %>)
       
           Platform:
           ---------
           x64-mingw32
       
       [2017-10-24T09:28:57+00:00] INFO: Running queued delayed notifications before re-raising exception
```

### PR DESCRIPTION
**Pull request by majormoses**
### Description

Prevent compilation failures in using config recipe when there are no handlers defined.

### Issues Resolved

#529 

### Check List

- [ ] All tests pass. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/TESTING.MD>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable
- [ ] All commits have been signed for the Developer Certificate of Origin. See <https://github.com/chef-cookbooks/community_cookbook_documentation/blob/master/CONTRIBUTING.MD>

### CODE REVIEW

**Comment by majormoses** [comment]
I can squash the commit, I kept them seperate in case someone still wanted some of the rendering that is functional and valid even if it does not do much.
